program = { function };

type = "Unit" | "Int";

function = "fun", IDENT, "(", params, ")", ":", type, "=", expr;

params_nonempty = [ "val" | "var" ], IDENT, ":", type, [ ",", params_nonempty ];
params = [ params_nonempty, [ "," ] ];

expr = "unit"
	 | INTEGER
     | IDENT
	 | prefix_op, expr
     | expr, infix_op, expr
	 | expr, suffix_op
	 | variable_definition
	 | funcall
	 | (expr)
	 | block
	 ;

prefix_op = "-";
infix_op = "+" | "=";
suffix_op = "!";

var_val = "val" | "var";
variable_definition = var_val, IDENT, ":", [ type ], "=", expr;

funcall = IDENT, "(", args, ")";

args_nonempty = expr, [ ",", args_nonempty ];
args = [ args_nonempty, [ "," ] ];

block = "{", block_inner, "}";

block_inner = [ expr, [ ";", block_inner ] ];
